name: Docker Build

on:
  workflow_call:
    inputs:
      push_to_registry:
        type: boolean
        default: false
      branch:
        type: string
        required: true
      platforms:
        type: string
        default: 'linux/amd64'
permissions:
  contents: read
  packages: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push GPU image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: gpu_build
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push_to_registry }}
          tags: |
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}-gpu
            ${{ env.IMAGE_NAME }}:latest-gpu
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push CPU image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: cpu_build
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.push_to_registry }}
          tags: |
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}-cpu
            ${{ env.IMAGE_NAME }}:latest-cpu
          cache-from: type=gha
          cache-to: type=gha,mode=max
